blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Ask a Question
    url: https://github.com/raphplt/QoreDB/discussions/new?category=q-a
    about: Please ask questions in our Discussions section.
